name = "basalt"
compatibility_date = "2024-10-24"
pages_build_output_dir = ".next"

[build]
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "20"

[[env.production]]
name = "basalt-production"
